################################### Default Configuration ############################
baseurl = "https://www.epiclines.nz/motorhome/"
title = "EpicLines Motorhomes"
theme = "vex-hugo"
# post excert
summarylength = "20"
# google analytics
googleAnalytics = "" # Ex: UA-123-45
languageCode = 'en-nz'
# disable language
disableLanguages = [] # disable language from here

# unsafe html
[markup.goldmark.renderer]
unsafe = true


#################################### Plugins ##########################################

# CSS Plugins
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap"
# Snipcard should be redundant once we implement Stripe
[[params.plugins.css]]
link = "https://cdn.snipcart.com/themes/v3.0.27/default/snipcart.css"
[[params.vendor.css]]
link = "vendor/bootstrap/bootstrap.min.css"
[[params.vendor.css]]
link = "vendor/themefisher-font/themefisher-font.min.css"
[[params.vendor.css]]
link = "vendor/slick/slick.min.css"

# JS Plugins
[[params.vendor.js]]
link = "vendor/jquery/jquery.js"
[[params.vendor.js]]
link = "vendor/bootstrap/bootstrap.min.js"
[[params.vendor.js]]
link = "vendor/slick/slick.min.js"



########################### Default parameters ##########################
[params]
logo = "images/logo.png"
logo_width = "100px"
logo_height = "30px"
# Meta data
description = "EpicLines Motorhomes"
author = "BinaryMist Limited"
copyright = '&copy; 2025 EpicLines - A division of BinaryMist Limited'
# currency
currency = "$"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io

motorhomeURL = "https://www.epiclines.nz/motorhome/"
coreURL = "https://www.epiclines.nz/"
surfURL = "https://www.epiclines.nz/surf/"

section = "motorhome"


# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Snipcart
[params.snipcart]
enable = false
# snipcart public api key
snipcart_api = "ZDgxY2ZiM2EtMWRmMi00M2ZkLWI1MDAtNzA2MDc0Y2Q1MzJlNjM3MTAzNDIwOTQ1NDA4NjM4"

# Subscription
[params.subscription]
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"                                                           # replace this code with yours

[taxonomies]
  # Product specific
  motor_home_detail = "motor-home/details"
  wood_product_type = "wood-product/types"  
  wood_product_suitablefor = "wood-product/suitable-for"
  wood_product_dimensions = "wood-product/dimensions"
  our_build_detail = "our-build/details"
  # Generic
  category = "categories"
  tag = "tags"
  # All others, 
  legal-resource = "legal-resources"
